# 现在支付接口
ipaynow:
  key: <%= ENV['WEBSTORE_IPAYNOW_KEY'] %>
  params:
    funcode: WP001
    appId: <%= ENV['WEBSTORE_IPAYNOW_APPID'] %>
    mhtOrderType: '01'
    mhtCurrencyType: 156
    notifyUrl: http://www.tenhs.com/api/payment/notify
    frontNotifyUrl: http://www.tenhs.com/api/payment/front_notify
    mhtCharset: UTF-8
    deviceType: '06'
    mhtSignType: MD5
