# 现在支付接口
ipaynow:
  key: <%= ENV['WEBSTORE_IPAYNOW_KEY'] %>
  params:
    funcode: WP001
    appId: <%= ENV['WEBSTORE_IPAYNOW_APPID'] %>
    mhtOrderType: '01'
    mhtCurrencyType: 156
    notifyUrl: http://www.tenhs.com/payment/notify
    frontNotifyUrl: http://www.tenhs.com/payment/front_notify
    mhtCharset: UTF-8
    deviceType: '06'
    mhtSignType: MD5

weixin:
  appid: <%= ENV['WECHAT_APP_ID'] %>
  appsecret: <%= ENV['WECHAT_APP_SECRET'] %>
  mch_id: <%= ENV['WECHAT_MCHID'] %>
  notify_url: http://www.tenhs.com/payment/wechat/notify
  access_token_url: http://wechat.tenhs.com/access_token
  prepay:
    host: api.mch.weixin.qq.com
    port: 443
    path: /pay/unifiedorder
    api_secret: <%= ENV['WECHAT_API_SECRET'] %>
  auth_access_token: #网页授权access_token
    host: api.weixin.qq.com
    port: 443
    path: /sns/oauth2/access_token
  notify:
    host: api.weixin.qq.com
    port: 443
    path: /cgi-bin/message/template/send
    order_delivery_template_id: 8YFfTusaXuASQxl4ThcBHdlxtQ111LQqj9ryEiDZouo
    order_template_id: LO2Uc3W6ieMNcyKrsnO-IYrGsHwduEzoy2fqc7enPQc
    order_created_template_id: 6m3HKdt6fF59n1qSfBLpRxuk-7QJF7hDp_4QWs2iVmo
    topcolor: '#989e4b'
    fontcolor: '#555'
  access_token:
    host: wechat.tenhs.com
    port: 80
    path: /access_token

alipay:
  pid: <%= ENV['ALIPAY_PARTNER_ID']%>
  seller_id: <%= ENV['ALIPAY_USER_ID'] %>
  key: <%= ENV['ALIPAY_KEY']%>
  mobile_pay:
    url: https://mapi.alipay.com/gateway.do
    service: alipay.wap.create.direct.pay.by.user
    payment_type: 1
    notify_url: http://www.tenhs.com/payment/alipay/notify
    return_url: http://www.tenhs.com/payment/alipay/front_notify
