# 现在支付接口
ipaynow:
  key: <%= ENV['WEBSTORE_IPAYNOW_KEY'] %>
  params:
    funcode: WP001
    appId: <%= ENV['WEBSTORE_IPAYNOW_APPID'] %>
    mhtOrderType: '01'
    mhtCurrencyType: 156
    notifyUrl: http://www.tenhs.com/api/payment/notify
    frontNotifyUrl: http://www.tenhs.com/api/payment/front_notify
    mhtCharset: UTF-8
    deviceType: '06'
    mhtSignType: MD5

weixin:
  appid: <%= ENV['WECHAT_APP_ID'] %>
  appsecret: <%= ENV['WECHAT_APP_SECRET'] %>
  mch_id: <%= ENV['WECHAT_MCHID'] %>
  notify_url: http://www.tenhs.com/api/payment/wechat/notify
  prepay:
    host: api.mch.weixin.qq.com
    port: 443
    path: /pay/unifiedorder
    api_secret: <%= ENV['WECHAT_API_SECRET'] %>
  access_token:
    host: api.weixin.qq.com
    port: 443
    path: /sns/oauth2/access_token

alipay:
  pid: <%= ENV['ALIPAY_PARTNER_ID']%>
  seller_id: <%= ENV['ALIPAY__ID'] %>
  key: <%= ENV['ALIPAY_KEY']%>
  mobile_pay:
    url: https://mapi.alipay.com/gateway.do
    service: alipay.wap.create.direct.pay.by.user
    payment_type: 1
    notify_url: http://www.tenhs.com/api/payment/alipay/notify
    return_url: http://www.tenhs.com/api/payment/alipay/front_notify
