# 现在支付接口
ipaynow:
  key: PMcs76K4gMR5X2pEKIKUZlh51HklH6Xf
  params:
    funcode: WP001
    appId: 1432532892819816
    mhtOrderType: '01'
    mhtCurrencyType: 156
    notifyUrl: http://www.tenhs.com/admin/payment/jsonp/ipaynow/notify
    frontNotifyUrl: http://www.tenhs.com/admin/payment/jsonp/ipaynow/front/notify
    mhtCharset: UTF-8
    deviceType: '06'
    mhtSignType: MD5
