# File upload configuration
development:
  base_url: http://upload.localhost/
  storage_path: /home/rexhouy/tmp/uploads/

test:
  base_url: http://upload.localhost/
  storage_path: /home/rexhouy/tmp/uploads/

production:
  base_url: <%=ENV["FILE_URL"]%>
  storage_path: /home/app/uploads/
